export const REQUEST = 'REQUEST'
export const RECIEVE = 'RECIEVE'
export const ERROR = 'ERROR'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGIST = 'USER_REGIST'
export const USER_CHECK_VCODE = 'USER_CHECK_VCODE'
export const USER_GETCURRENT = 'USER_GETCURRENT'
export const USER_GETWXMPS = 'USER_GETWXMPS'

export const POST_SAVE = 'POST_SAVE'
export const POST_GET_BY_ID = 'POST_GET_BY_ID'
export const POST_GET_BY_URL = 'POST_GET_BY_URL'
export const POST_RENDER = 'POST_RENDER'
export const POST_INSERT = 'POST_INSERT'
export const POST_SET = 'POST_SET'
export const POST_CLEAR = 'POST_CLEAR'
export const POST_LOAD = 'POST_LOAD'
export const POST_PREVIEW = 'POST_PREVIEW'
export const POST_SYNC = 'POST_SYNC'

export const STYLE_GET = 'STYLE_GET'
export const STYLE_RENDER = 'STYLE_RENDER'

export const IMAGES_GET = 'IMAGES_GET'
export const IMAGES_RENDER = 'IMAGES_RENDER'
export const IMAGES_SAVE = 'IMAGES_SAVE'
export const IMAGES_SEARCH = 'IMAGES_SEARCH'
export const IMAGES_DEL = 'IMAGES_DEL'
export const UPLOAD = 'UPLOAD'

export const ALERT_SHOW = 'ALERT_SHOW'
export const ALERT_CLOSE = 'ALERT_CLOSE'
