export const REQUEST = 'REQUEST'
export const REQUEST_SUCC = 'REQUEST_SUCC'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const REQUEST_LOADING = 'REQUEST_LOADING'

export const GET_OPTION_POST_LIST = 'GET_OPTION_POST_LIST'
export const GET_COMMON_STYLE = 'GET_COMMON_STYLE'
export const GET_USER_PICS = 'GET_USER_PICS'
export const SELECT_PIC = 'SELECT_PIC'
export const SELECT_PICS_CANCEL = 'SELECT_PICS_CANCEL'
export const SELECT_PICS_CONFIRM = 'SELECT_PICS_CONFIRM'
export const SELECT_PICS_OPEN = 'SELECT_PICS_OPEN'

export const PICK_PIC = 'PICK_PIC'
